# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Amule
version: "0.0.0"
slug: example
description: aMule add-on
url: "https://github.com/davoloko/hassio-addons/tree/master/amule"
apparmor: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
webui: http://[HOST]:4711
startup: services
ingress: false
map:
  - config:rw
  - share:rw
  - media:rw
  - ssl
options: {
  PUID: 1000,
  PGID: 1000,
  TZ: Europe/Madrid,
  GUI_PWD: <fill_password>,
  WEBUI_PWD: <fill_password>,
  MOD_AUTO_RESTART_ENABLED: true,
  MOD_AUTO_RESTART_CRON: 0 6 * * *,
  MOD_AUTO_SHARE_ENABLED: false,
  MOD_AUTO_SHARE_DIRECTORIES: /incoming;/my_movies,
  MOD_FIX_KAD_GRAPH_ENABLED: true,
}
ports: {
  "4711": 4711,
  "4712": 4712,
  "4662": 4662,
  "4665/udp": 4665,
  "4672/udp": 4672,
}
port_description: {
  4711: "web ui",
  4712: "remote gui, webserver, cmd ...",
  4662: "ed2k tcp",
  4665/udp: "ed2k global search udp (tcp port +3)",
  4672/udp: "ed2k udp",
}
schema:
  PUID: int,
  PGID: int,
  TZ: str?,
  GUI_PWD: str?,